title: Stackbit Fresh Theme
baseURL: /
params:
  layout_style: overflow
  palette: blue
  header:
    type: header
    template: header
    title: Tom Hall
    tagline: Personal Site
    profile_img: /images/tom(1).jpg
    profile_img_alt: Author avatar
    background: dark
    has_nav: true
    nav_links:
      - type: action
        template: action
        label: Home
        url: /
        style: link
      - type: action
        template: action
        label: Blog
        url: /blog/
        style: link
      - type: action
        template: action
        label: Style Guide
        url: /style-guide/
        style: link
      - type: action
        template: action
        label: About
        url: /about/
        style: link
      - type: action
        template: action
        label: Contact
        url: /contact/
        style: link
    has_social: true
    social_links:
      - type: action
        template: action
        label: Instagram
        url: 'https://www.youtube.com/'
        style: icon
        icon_class: youtube
        new_window: true
      - type: action
        template: action
        label: GitHub
        url: 'https://github.com/halltom'
        style: icon
        icon_class: github
        new_window: true
      - type: action
        template: action
        label: LinkedIn
        url: 'https://www.linkedin.com/in/thomas-h-34853518a'
        style: icon
        icon_class: linkedin
        new_window: true
  footer:
    type: footer
    template: footer
    content: '&copy; tom. All rights reserved </a>'
  domain: 'https://tom-a56cc.netlify.app'
taxonomies:
  stub: stub
disableKinds:
  - RSS
  - taxonomy
  - taxonomyTerm
markup:
  goldmark:
    renderer:
      unsafe: true
